spring:
  application:
    name: schedule

  datasource:
    url: jdbc:postgresql://localhost:5433/scheduler_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  mail:
    host: smtp.gmail.com
    username: alexshamox@gmail.com
    password: nroj zayu qugl fosl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: alexshamox@gmail.com

server:
  port: 8081
  forward-headers-strategy: framework

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 3600000


admin:
  email: mainAdmin@gmail.com
  password: mainAdmin123!
